name: uhk_events
description: UHK Events
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http:

  # State management
  flutter_bloc: ^3.0.0

  # NoSQL storage
  hive: ^1.3.0
  hive_flutter: ^0.3.0

  # Firebase
  firebase_core: ^0.4.0+9
  cloud_firestore: ^0.12.9+5
  firebase_messaging: ^6.0.9
  firebase_auth: ^0.14.0+5

  google_maps_flutter: ^0.5.21+8

  # Tools
  intl: 0.16.1
  flutter_i18n: 0.8.3
  equatable: ^0.6.1
  flutter_svg: ^0.14.4
  transparent_image: ^1.0.0
  path_provider: ^1.3.0
  connectivity: ^0.4.6+2
  get_it: ^3.1.0
  print_lumberdash: ^2.1.0
  data_connection_checker: ^0.3.4
  either_option: ^1.0.5

  cupertino_icons: ^0.1.2

  shimmer: ^1.0.1
  add_2_calendar: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: 0.7.0
  build_runner: ^1.7.2
  bloc_test: ^3.0.0
  pedantic: ^1.8.0
  flutter_launcher_icons: ^0.7.3

flutter_icons:
  image_path: "assets/launcher/uhk_events.png"
  android: true
  ios: true

flutter:
  assets:
    - assets/i18n/
    - assets/icons/

  fonts:
    - family: Comenia Sans
      fonts:
        - asset: assets/fonts/ComeniaSans.otf
        - asset: assets/fonts/ComeniaSansBold.otf
          weight: 700


