name: uhk_events
description: UHK Events
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http:

  # State management
  flutter_bloc: ^3.0.0

  # NoSQL storage
  hive: 1.1.1
  hive_flutter: 0.2.1

  # Firebase
  firebase_core: ^0.4.0+9
  cloud_firestore: ^0.12.9+5
  firebase_messaging: ^5.1.6
  firebase_auth: ^0.14.0+5

  google_maps_flutter: ^0.5.21+8

  # Tools
  intl: 0.16.0
  equatable: ^0.6.1
  flutter_svg: ^0.14.4
  transparent_image: ^1.0.0
  path_provider: ^1.3.0

  cupertino_icons: ^0.1.2

  flutter_i18n: 0.8.0
  shimmer: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: 0.5.2
  build_runner:
  bloc_test: ^3.0.0
  pedantic: ^1.8.0


flutter:
  assets:
    - assets/i18n/
    - assets/icons/

  fonts:
    - family: Comenia Sans
      fonts:
        - asset: assets/fonts/ComeniaSans.otf
        - asset: assets/fonts/ComeniaSansBold.otf
          weight: 700


